import React, { useMemo, useState } from 'react';
import { View, useWindowDimensions, Pressable } from 'react-native';
import { Search, SlidersHorizontal, Plus, Heart, ArrowUp, ArrowDown, Pencil, Trash2, Wind, X, Check, Sparkles } from 'lucide-react-native';
import { useAppStore } from '../hooks/useAppStore';
import { BreathingExercise, BreathingPattern } from '../types';
import { fonts, useTheme } from '../theme';
import { Button, Text, Input, Chip, IconButton, Modal, Stepper, EmptyState, Divider } from '../components/ui';
import { ExerciseCard } from '../components/ExerciseCard';
import { CATEGORIES } from '../data/exercises';
import { getRecommendations } from '../analytics';

const featuredCategories=['All practices','Calm','Focus','Energy','Sleep','Stress Relief'];
export function ExploreScreen({onStart,onToast,onlyFavorites=false}:{onStart:(e:BreathingExercise)=>void;onToast:(s:string)=>void;onlyFavorites?:boolean}) {
 const {colors}=useTheme();const store=useAppStore();const{exercises,sessions,favorites,customExercises,reorderFavorite,deleteCustomExercise}=store;const{width}=useWindowDimensions();const cols=width<680?1:width<1180?2:3;
 const [search,setSearch]=useState('');const[category,setCategory]=useState('All practices');const[tab,setTab]=useState<'all'|'custom'>('all');const[filterOpen,setFilterOpen]=useState(false);const[difficulty,setDifficulty]=useState('Any level');const[duration,setDuration]=useState('Any duration');const[showCategories,setShowCategories]=useState(false);const[custom,setCustom]=useState<BreathingExercise|'new'|null>(null);const[remove,setRemove]=useState<BreathingExercise|null>(null);
 const recommendations=useMemo(()=>getRecommendations(sessions,favorites,exercises),[sessions,favorites,exercises]);
 const items=useMemo(()=>{let list=onlyFavorites?favorites.map(id=>exercises.find(e=>e.id===id)).filter((e):e is BreathingExercise=>!!e):tab==='custom'?customExercises:[...exercises].sort((a,b)=>b.popularity-a.popularity);return list.filter(e=>(category==='All practices'||e.category===category)&&(difficulty==='Any level'||e.difficulty===difficulty)&&(duration==='Any duration'||duration==='1–5 min'&&e.duration<=5||duration==='5–10 min'&&e.duration>5&&e.duration<=10||duration==='10–20 min'&&e.duration>10&&e.duration<=20||duration==='20+ min'&&e.duration>20)&&[e.name,e.category,e.description].join(' ').toLowerCase().includes(search.toLowerCase().trim()))},[onlyFavorites,tab,exercises,favorites,customExercises,category,difficulty,duration,search]);
 const filtered=difficulty!=='Any level'||duration!=='Any duration';
 return <View style={{gap:26}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:15}}><View style={{flex:1}}><Text variant="caption" muted>{onlyFavorites?'YOUR PERSONAL COLLECTION':'A PRACTICE FOR EVERY MOMENT'}</Text><Text variant="display" style={{marginTop:8,fontSize:width<680?35:42,lineHeight:51}}>{onlyFavorites?'The ones you come back to.':'Find your breathing space.'}</Text><Text muted style={{marginTop:7}}>{onlyFavorites?'Your favorite rituals, always close at hand.':'Meet yourself where you are. Find a rhythm that feels right.'}</Text></View>{width>=900&&<Button label="Create a practice" icon={Plus} onPress={()=>setCustom('new')} variant="secondary" style={{marginTop:24}}/>}</View>
 {!onlyFavorites&&<View style={{flexDirection:'row',borderBottomWidth:1,borderColor:colors.line,gap:28}}>{([{id:'all',label:'All practices'},{id:'custom',label:'Made by you'}] as const).map(t=><Pressable key={t.id} accessibilityRole="tab" accessibilityState={{selected:tab===t.id}} onPress={()=>setTab(t.id)} style={{paddingBottom:15,paddingTop:5,borderBottomWidth:2,borderBottomColor:tab===t.id?colors.primary:'transparent'}}><Text style={{color:tab===t.id?colors.primary:colors.muted,fontFamily:fonts.medium,fontSize:13}}>{t.label}{t.id==='custom'?'  '+customExercises.length:''}</Text></Pressable>)}</View>}
 <View style={{flexDirection:'row',alignItems:'center',gap:12}}><View style={{flex:1,position:'relative'}}><Input value={search} onChangeText={setSearch} placeholder="Search for a little calm, energy, focus…" accessibilityLabel="Search breathing exercises" style={{paddingLeft:44,minHeight:49,borderRadius:14}}/><View pointerEvents="none" style={{position:'absolute',left:15,top:16}}><Search size={17} color={colors.muted}/></View>{search!==''&&<IconButton icon={X} label="Clear search" onPress={()=>setSearch('')} style={{position:'absolute',right:5,top:3}}/>}</View><Button label={filtered?'Filtered':'Filters'} icon={SlidersHorizontal} onPress={()=>setFilterOpen(true)} variant="secondary"/></View>
 <View style={{flexDirection:'row',gap:8,flexWrap:'wrap'}}>{(showCategories?['All practices',...CATEGORIES]:featuredCategories).map(c=><Chip key={c} label={c} selected={category===c} onPress={()=>setCategory(c)} style={{borderRadius:30}}/>)}<Chip label={showCategories?'Less':'More goals +'} onPress={()=>setShowCategories(!showCategories)}/></View>
 {!onlyFavorites&&tab==='all'&&category==='All practices'&&!search&&!filtered&&recommendations[0]&&<Pressable accessibilityRole="button" accessibilityLabel={'Try '+recommendations[0].exercise.name} onPress={()=>onStart(recommendations[0].exercise)} style={{padding:20,backgroundColor:colors.primaryLight,borderRadius:18,flexDirection:'row',alignItems:'center',gap:16}}><Sparkles size={22} color={colors.primary}/><View style={{flex:1}}><Text variant="small" style={{fontFamily:fonts.semibold}}>{recommendations[0].title}</Text><Text variant="small" muted style={{marginTop:3}}>{recommendations[0].description}</Text></View><Text variant="small" style={{color:colors.primary}}>Try it →</Text></Pressable>}
 <View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Text variant="small" muted>{items.length} {items.length===1?'practice':'practices'}{onlyFavorites?' saved for you':tab==='custom'?' made by you':' to make your own'}</Text>{width<900&&<Button label="Create" icon={Plus} small variant="ghost" onPress={()=>setCustom('new')}/>}</View>
 {items.length?<View style={{flexDirection:'row',flexWrap:'wrap',marginHorizontal:-9,rowGap:20}}>{items.map(e=><View key={e.id} style={{width:(100/cols+'%') as any,paddingHorizontal:9}}><ExerciseCard exercise={e} onPress={()=>onStart(e)}/>{(onlyFavorites||e.custom)&&<View style={{flexDirection:'row',justifyContent:'flex-end',alignItems:'center',paddingHorizontal:7,paddingTop:5,gap:0}}>{onlyFavorites&&<><Text variant="small" muted style={{marginRight:'auto',fontSize:10}}>Set your own order</Text><IconButton icon={ArrowUp} label={'Move '+e.name+' earlier'} onPress={()=>reorderFavorite(e.id,-1)}/><IconButton icon={ArrowDown} label={'Move '+e.name+' later'} onPress={()=>reorderFavorite(e.id,1)}/></>}{e.custom&&<><IconButton icon={Pencil} label={'Edit '+e.name} onPress={()=>setCustom(e)}/><IconButton icon={Trash2} label={'Delete '+e.name} onPress={()=>setRemove(e)}/></>}</View>}</View>)}</View>:<EmptyState icon={onlyFavorites?Heart:Wind} title={search||filtered||category!=='All practices'?'A little more space to explore.':onlyFavorites?'Keep your favorites close.':'A rhythm, entirely your own.'} description={search||filtered||category!=='All practices'?'Try a different search or clear the filters to find your next practice.':onlyFavorites?'Tap the heart on an exercise to save it here for another moment.':'Create a breathing pattern that feels comfortable for you.'} action={search||filtered||category!=='All practices'?'Clear filters':onlyFavorites?undefined:'Create a practice'} onAction={()=>{if(search||filtered||category!=='All practices'){setSearch('');setCategory('All practices');setDifficulty('Any level');setDuration('Any duration')}else setCustom('new')}}/>}
 <Modal visible={filterOpen} onClose={()=>setFilterOpen(false)} title="Find your rhythm" subtitle="A little guidance to narrow things down."><View style={{gap:23}}><Text variant="label">Time for yourself</Text><View style={{flexDirection:'row',gap:8,flexWrap:'wrap'}}>{['Any duration','1–5 min','5–10 min','10–20 min','20+ min'].map(x=><Chip key={x} label={x} selected={duration===x} onPress={()=>setDuration(x)}/>)}</View><Text variant="label">Comfort level</Text><View style={{flexDirection:'row',gap:8,flexWrap:'wrap'}}>{['Any level','Beginner','Intermediate','Advanced'].map(x=><Chip key={x} label={x} selected={difficulty===x} onPress={()=>setDifficulty(x)}/>)}</View><Button label={'Show '+items.length+' practices'} icon={Check} onPress={()=>setFilterOpen(false)}/><Button label="Reset filters" variant="ghost" onPress={()=>{setDifficulty('Any level');setDuration('Any duration')}}/></View></Modal>
 {custom&&<CustomForm exercise={custom==='new'?undefined:custom} onClose={()=>setCustom(null)} onSave={()=>{setCustom(null);onToast('Your practice is saved. Make it a little daily ritual.');setTab('custom')}}/>}
 <Modal visible={!!remove} onClose={()=>setRemove(null)} title="Let this practice go?" subtitle="Completed sessions will stay in your journey."><Text muted>This removes {remove?.name} from your custom practices and favorites.</Text><View style={{flexDirection:'row',gap:12,marginTop:25}}><Button label="Keep practice" variant="secondary" onPress={()=>setRemove(null)} style={{flex:1}}/><Button label="Delete practice" onPress={()=>{if(remove)deleteCustomExercise(remove.id);setRemove(null);onToast('Custom practice deleted.')}} style={{flex:1,backgroundColor:colors.danger}}/></View></Modal>
 </View>
}

function CustomForm({exercise,onClose,onSave}:{exercise?:BreathingExercise;onClose:()=>void;onSave:()=>void}) {
 const{saveCustomExercise}=useAppStore();const{colors}=useTheme();const[name,setName]=useState(exercise?.name||'');const[category,setCategory]=useState(exercise?.category||'Calm');const[pattern,setPattern]=useState<BreathingPattern>(exercise?.pattern||{inhale:4,hold:0,exhale:6,rest:0});const[rounds,setRounds]=useState(exercise?.rounds||5);const[error,setError]=useState('');const seconds=Object.values(pattern).reduce((a,b)=>a+b,0)*rounds;
 const save=()=>{if(!name.trim()){setError('Give your practice a name first.');return}try{saveCustomExercise({id:exercise?.id||'custom-'+Date.now().toString(36),name:name.trim(),category,description:'Your personal rhythm. '+pattern.inhale+'s in, '+pattern.exhale+'s out, one moment at a time.',duration:Math.max(1,Math.round(seconds/60)),difficulty:'Beginner',pattern,rounds,icon:'leaf-outline',color:'#7D9B77',tint:'#E4EEE7',popularity:50,custom:true});onSave()}catch(e){setError(e instanceof Error?e.message:'This practice could not be saved.')}};
 return <Modal visible onClose={onClose} title={exercise?'Refine your rhythm':'A rhythm of your own'} subtitle="Keep it comfortable. There is no perfect pattern."><View style={{gap:20}}><Input label="Practice name" placeholder="My morning moment" value={name} onChangeText={setName} maxLength={60}/><Text variant="label">What is this moment for?</Text><View style={{flexDirection:'row',gap:7,flexWrap:'wrap'}}>{['Calm','Focus','Energy','Sleep','Balance','Meditation'].map(c=><Chip key={c} label={c} selected={category===c} onPress={()=>setCategory(c)}/>)}</View><Divider/><View style={{flexDirection:'row',justifyContent:'space-around',paddingVertical:12,borderRadius:18,backgroundColor:colors.primaryLight}}>{Object.entries(pattern).map(([key,val])=><View key={key} style={{alignItems:'center',gap:5}}><Text variant="title">{val}s</Text><Text variant="small" muted style={{textTransform:'capitalize'}}>{key}</Text></View>)}</View>{(['inhale','hold','exhale','rest'] as const).map(key=><Stepper key={key} label={key[0].toUpperCase()+key.slice(1)} value={pattern[key]} onChange={n=>setPattern({...pattern,[key]:n})} min={key==='inhale'||key==='exhale'?1:0} max={30} suffix="s"/>)}<Divider/><Stepper label="Rounds" value={rounds} onChange={setRounds} min={1} max={100}/><Text variant="small" muted style={{textAlign:'center'}}>Your practice · {Math.floor(seconds/60)} min {seconds%60} sec · {rounds} rounds</Text>{!!error&&<Text style={{color:colors.danger}}>{error}</Text>}<Button label={exercise?'Save changes':'Save my practice'} onPress={save} icon={Check}/></View></Modal>
}
