import React, { useMemo, useState } from 'react';
import { View, Pressable, useWindowDimensions } from 'react-native';
import Svg, { Circle } from 'react-native-svg';
import { ArrowRight, ArrowUpRight, Sun, Moon, CloudSun, Wind, Leaf, Zap, Focus, Flame, Clock3, Check } from 'lucide-react-native';
import { Text, Card, Button, Chip, SectionTitle } from '../components/ui';
import { BreathingOrb } from '../components/BreathingOrb';
import { ExerciseCard } from '../components/ExerciseCard';
import { useTheme, fonts } from '../theme';
import { useAppStore } from '../hooks/useAppStore';
import { getAnalytics, getRecommendations, localDateKey } from '../analytics';
import { BreathingExercise } from '../types';
import { LinearGradient } from 'expo-linear-gradient';

const moods=[{label:'A little stressed',icon:Wind,exercise:'calm-reset'},{label:'Low on energy',icon:Zap,exercise:'energy-boost'},{label:'A busy mind',icon:Focus,exercise:'clear-mind'},{label:'Ready to unwind',icon:Moon,exercise:'deep-relaxation'}];
export function HomeScreen({onStart,onExplore,onProgress,onJourney,onPersonalize}:{onStart:(e:BreathingExercise)=>void;onExplore:()=>void;onProgress:()=>void;onJourney:()=>void;onPersonalize:()=>void}) {
 const{colors,isDark,reducedMotion}=useTheme();const store=useAppStore();const{preferences:p,sessions,exercises,demoMode,favorites}=store;const{width}=useWindowDimensions();const mobile=width<760;const narrow=width<1150;const [mood,setMood]=useState('');const stats=useMemo(()=>getAnalytics(sessions),[sessions]);const recs=useMemo(()=>getRecommendations(sessions,favorites,exercises),[sessions,exercises,favorites]);const selected=exercises.find(e=>e.id===(moods.find(m=>m.label===mood)?.exercise||'calm-reset'))||exercises[0];const hour=new Date().getHours();const greeting=hour<12?'Good morning':hour<17?'Good afternoon':'Good evening';const GreetingIcon=hour<12?Sun:hour<18?CloudSun:Moon;const progress=Math.min(1,stats.todayMinutes/p.dailyGoal);const recent=[...sessions].sort((a,b)=>b.completedAt.localeCompare(a.completedAt)).slice(0,3);const featured=['calm-reset','box-breathing','deep-relaxation'].map(id=>exercises.find(e=>e.id===id)!).filter(Boolean);
 return <View style={{gap:30}}>
 <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:15}}><View style={{flex:1}}><View style={{flexDirection:'row',gap:8,alignItems:'center',marginBottom:8}}><GreetingIcon size={16} color={colors.sage}/><Text variant="small" muted>{greeting}, {p.name||'Masud'}</Text></View><Text variant="display" style={{fontSize:mobile?34:42,lineHeight:mobile?43:53}}>A little space for yourself.</Text><Text muted style={{marginTop:8,fontSize:13}}>Let the world wait. Come back to your breath.</Text></View>{!mobile&&<View style={{flexDirection:'row',gap:7,paddingHorizontal:14,paddingVertical:9,borderRadius:30,backgroundColor:colors.cream}}><Flame size={16} color={isDark?'#A38B57':colors.pink}/><Text variant="small" style={{color:isDark?colors.ink:colors.pink,fontFamily:fonts.medium}}>{stats.currentStreak} day streak</Text></View>}</View>
 <View style={{flexDirection:mobile?'column':'row',gap:16,alignItems:mobile?'flex-start':'center'}}><Text variant="small" style={{fontFamily:fonts.medium,marginRight:3}}>How are you feeling?</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8,flex:1}}>{moods.map(m=><Chip key={m.label} label={m.label} icon={m.icon} selected={mood===m.label} onPress={()=>setMood(mood===m.label?'':m.label)} style={{paddingHorizontal:mobile?12:14,borderRadius:30,minHeight:36}}/>)}</View></View>
 <View style={{flexDirection:mobile?'column':'row',gap:20}}>
 <View style={{flex:mobile?undefined:2.12,minHeight:mobile?540:322,borderRadius:26,overflow:'hidden',borderWidth:1,borderColor:colors.heroLine}}>
 <LinearGradient colors={isDark?[colors.heroStart,colors.heroEnd]:[colors.heroStart,colors.heroMiddle,colors.heroEnd]} start={{x:0,y:0}} end={{x:1,y:1}} style={{flex:1,padding:mobile?25:32,justifyContent:'space-between'}}>
 <View style={{flexDirection:'row',alignItems:'center',gap:7}}><Leaf size={13} color={colors.primary}/><Text variant="caption" style={{fontSize:9,color:colors.primary,letterSpacing:1.8}}>YOUR DAILY RESET</Text></View>
 <View style={{zIndex:2,alignItems:'flex-start',marginTop:mobile?20:24,marginBottom:mobile?210:0}}><Text variant="heading" style={{fontSize:mobile?33:narrow?30:36,lineHeight:mobile?42:46,maxWidth:320}}>{mood?selected.name+'.\nA moment for you.':'Inhale calm.\nExhale the rest.'}</Text><Text variant="small" style={{marginTop:13,maxWidth:mobile?220:255,color:colors.muted,lineHeight:20}}>A few mindful minutes can make room{!mobile?'\n':' '}for a whole new kind of day.</Text><Button label="Start breathing" icon={ArrowRight} onPress={()=>onStart(selected)} style={{marginTop:24,borderRadius:13,paddingHorizontal:22,minHeight:48}}/><View style={{flexDirection:'row',alignItems:'center',gap:6,marginTop:13}}><Clock3 size={11} color={colors.muted}/><Text style={{fontSize:10,color:colors.muted}}>{selected.duration} min</Text><Text style={{fontSize:10,color:colors.muted}}>·</Text><Text style={{fontSize:10,color:colors.muted}}>{selected.name}</Text></View></View>
 <View pointerEvents="none" style={{position:'absolute',right:mobile?12:narrow?-58:-25,top:mobile?260:12,opacity:1}}><BreathingOrb size={mobile?260:narrow?280:340} idle reducedMotion={reducedMotion}/></View><View style={{position:'absolute',right:mobile?40:54,bottom:mobile?18:23,alignItems:'center'}}><Text style={{fontSize:10,letterSpacing:.3,color:colors.muted}}>Ready when you are.</Text></View>
 </LinearGradient></View>
 <Card style={{flex:mobile?undefined:1,padding:24,alignItems:'center',justifyContent:'space-between',minWidth:mobile?undefined:230}}><View style={{alignSelf:'stretch',flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Text style={{fontFamily:fonts.medium,fontSize:14}}>Your daily rhythm</Text><Pressable accessibilityRole="button" accessibilityLabel="View your progress" onPress={onProgress}><ArrowUpRight size={17} color={colors.muted}/></Pressable></View><View style={{flexDirection:width<400?'column':mobile?'row':'column',alignItems:'center',gap:mobile?16:0,marginVertical:mobile?18:12}}><View style={{height:146,width:146,justifyContent:'center',alignItems:'center'}}><Svg width={146} height={146} style={{position:'absolute'}}><Circle cx={73} cy={73} r={63} fill="none" stroke={colors.surfaceAlt} strokeWidth={6}/><Circle cx={73} cy={73} r={63} fill="none" stroke={isDark?colors.sage:colors.lilac} strokeWidth={6} strokeDasharray={progress*396+' 396'} strokeLinecap="round" transform="rotate(-90 73 73)"/></Svg><Text style={{fontFamily:fonts.serif,fontSize:38,lineHeight:47}}>{Number(stats.todayMinutes.toFixed(1))}<Text style={{fontSize:17,color:colors.muted}}> / {p.dailyGoal}</Text></Text><Text style={{fontSize:10,color:colors.muted,marginTop:1}}>mindful minutes</Text></View><View style={{alignItems:'center'}}><Text variant="small" style={{fontFamily:fonts.medium}}>{progress>=1?'Your daily goal, beautifully met.':'Every breath is a fresh start.'}</Text><Text style={{fontSize:10,color:colors.muted,marginTop:4}}>{stats.todaySessions} sessions today{demoMode?' · Sample activity':''}</Text></View></View>
 <View style={{flexDirection:'row',justifyContent:'space-between',width:'100%',borderTopWidth:1,borderColor:colors.line,paddingTop:15}}>{stats.weekDays.map(day=><View key={day.date} style={{alignItems:'center',gap:7}}><View style={{height:24,width:24,backgroundColor:day.minutes>0?colors.primaryLight:colors.background,borderRadius:12,alignItems:'center',justifyContent:'center',borderWidth:day.date===localDateKey(new Date())?1:0,borderColor:colors.sage}}>{day.minutes>0?<Check size={11} color={colors.primary}/>:<View style={{width:3,height:3,borderRadius:2,backgroundColor:colors.subtle}}/>}</View><Text style={{fontSize:9,color:colors.muted}}>{day.label.slice(0,1)}</Text></View>)}</View></Card>
 </View>
 <View><SectionTitle title="Find your kind of calm" subtitle="A small practice. A meaningful shift." action="Explore all" onAction={onExplore}/><View style={{flexDirection:mobile?'column':'row',gap:18}}>{featured.map(e=><ExerciseCard key={e.id} exercise={e} onPress={()=>onStart(e)} compact={!mobile}/>)}</View></View>
 <View style={{flexDirection:mobile?'column':'row',gap:20}}><Card style={{flex:1.2}}><SectionTitle title="A little more, every day" action="Your progress" onAction={onProgress}/><View style={{flexDirection:'row',alignItems:'baseline',gap:7,marginBottom:12}}><Text style={{fontFamily:fonts.serif,fontSize:30}}>{Math.round(stats.weekMinutes)}</Text><Text variant="small" muted>mindful minutes this week</Text></View><View style={{height:95,flexDirection:'row',gap:mobile?17:24,alignItems:'flex-end',paddingHorizontal:4}}>{stats.weekDays.map(d=><View key={d.date} style={{flex:1,alignItems:'center',height:'100%',justifyContent:'flex-end',gap:8}}><View accessibilityLabel={d.label+', '+d.minutes+' minutes'} style={{height:Math.max(4,d.minutes/Math.max(1,...stats.weekDays.map(x=>x.minutes))*67),backgroundColor:d.date===localDateKey(new Date())?colors.primary:colors.accent,width:'100%',maxWidth:35,borderRadius:5}}/><Text style={{fontSize:9,color:colors.muted}}>{d.label.slice(0,3)}</Text></View>)}</View></Card>
 <Card style={{flex:1}}><SectionTitle title="Continue your practice" action="History" onAction={onJourney}/>{recent.length?recent.map((s,i)=><Pressable key={s.id} accessibilityRole="button" accessibilityLabel={'Start '+s.exerciseName+' again'} onPress={()=>onStart(exercises.find(e=>e.id===s.exerciseId)||exercises[0])} style={({pressed})=>[{flexDirection:'row',gap:12,alignItems:'center',paddingVertical:10,borderBottomWidth:i<recent.length-1?1:0,borderColor:colors.line,opacity:pressed?.6:1}]}><View style={{width:34,height:34,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:colors.surfaceAlt}}><Wind size={16} color={colors.sage}/></View><View style={{flex:1}}><Text variant="small" style={{fontFamily:fonts.medium}}>{s.exerciseName}</Text><Text style={{fontSize:10,color:colors.muted,marginTop:2}}>{Math.round(s.durationSeconds/60)} min · {new Date(s.completedAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</Text></View><ArrowUpRight size={15} color={colors.muted}/></Pressable>):<View style={{paddingVertical:20}}><Text muted>Your journey starts with one breath.</Text><Button label="Find your first practice" variant="ghost" onPress={onExplore} style={{alignSelf:'flex-start',paddingHorizontal:0,marginTop:8}}/></View>}</Card></View>
 {recs[0]&&<Pressable onPress={()=>onStart(recs[0].exercise)} accessibilityRole="button" style={{flexDirection:'row',alignItems:'center',padding:20,borderRadius:18,backgroundColor:colors.primaryLight,gap:15}}><Leaf size={20} color={colors.primary}/><View style={{flex:1}}><Text variant="small" style={{fontFamily:fonts.medium}}>{recs[0].title}</Text><Text variant="small" muted style={{marginTop:3}}>{recs[0].description}</Text></View><ArrowRight size={18} color={colors.primary}/></Pressable>}
 <View style={{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,paddingVertical:5}}><Leaf size={13} color={colors.sage}/><Text variant="small" muted style={{fontSize:11}}>There’s no perfect way to begin. Just begin.</Text></View>
 </View>
}
