import React from 'react';
import { Pressable, View, Text as RNText, TextProps, StyleSheet, ViewStyle, StyleProp, Modal as RNModal, ScrollView, Switch, TextInput, Platform } from 'react-native';
import { ArrowRight, X, Plus, Minus, ChevronRight, type LucideIcon } from 'lucide-react-native';
import { fonts, shadow, useTheme } from '../theme';

export function Text({variant='body',muted=false,style,...props}:TextProps & {variant?:'body'|'small'|'caption'|'label'|'title'|'heading'|'display';muted?:boolean}) {const t=useTheme();return <RNText {...props} style={[{fontFamily:fonts.regular,color:muted?t.colors.muted:t.colors.ink,fontSize:14,lineHeight:21},typeStyles[variant],t.largeText&&{fontSize:(typeStyles[variant]?.fontSize||14)*1.15,lineHeight:(typeStyles[variant]?.lineHeight||21)*1.15},style]}/>}
const typeStyles=StyleSheet.create({body:{fontSize:14,lineHeight:22},small:{fontSize:12,lineHeight:18},caption:{fontSize:10,lineHeight:16,letterSpacing:1.6,fontFamily:fonts.semibold},label:{fontSize:13,lineHeight:20,fontFamily:fonts.medium},title:{fontSize:23,lineHeight:31,fontFamily:fonts.serif},heading:{fontSize:32,lineHeight:41,fontFamily:fonts.serif},display:{fontSize:44,lineHeight:54,fontFamily:fonts.serif}});
export function Card({children,style,...props}:React.ComponentProps<typeof View>){const{colors}=useTheme();return <View {...props} style={[{backgroundColor:colors.surface,borderRadius:24,borderWidth:1,borderColor:colors.line,padding:24},shadow,style]}>{children}</View>}
export function Button({label,onPress,variant='primary',icon:Icon,style,disabled=false,small=false,testID}:{label:string;onPress:()=>void;variant?:'primary'|'secondary'|'ghost';icon?:LucideIcon;style?:StyleProp<ViewStyle>;disabled?:boolean;small?:boolean;testID?:string}) {const{colors}=useTheme();const color=variant==='primary'?colors.white:colors.primary;return <Pressable testID={testID} accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={({pressed,hovered}:any)=>[{minHeight:small?42:50,paddingHorizontal:small?16:23,borderRadius:14,flexDirection:'row',gap:12,alignItems:'center',justifyContent:'center',backgroundColor:variant==='primary'?colors.primary:variant==='secondary'?colors.surfaceAlt:'transparent',borderWidth:variant==='secondary'?1:0,borderColor:colors.line,opacity:disabled?.4:pressed?.78:1,transform:[{scale:pressed?.98:1}]},hovered&&{opacity:.86},style]}><Text style={{fontFamily:fonts.medium,fontSize:13,color}}>{label}</Text>{Icon&&<Icon size={16} color={color} strokeWidth={1.8}/>}</Pressable>}
export function IconButton({icon:Icon,label,onPress,color,active=false,style}:{icon:LucideIcon;label:string;onPress:()=>void;color?:string;active?:boolean;style?:StyleProp<ViewStyle>}) {const{colors}=useTheme();return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({pressed})=>[{width:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:22,backgroundColor:active?colors.primaryLight:'transparent',opacity:pressed?.5:1},style]}><Icon size={19} color={color||colors.ink} strokeWidth={1.65}/></Pressable>}
export function Chip({label,selected,onPress,icon:Icon,style}:{label:string;selected?:boolean;onPress:()=>void;icon?:LucideIcon;style?:StyleProp<ViewStyle>}) {const{colors}=useTheme();return <Pressable accessibilityRole="button" accessibilityState={{selected:!!selected}} onPress={onPress} style={({pressed})=>[{paddingHorizontal:16,minHeight:39,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,borderRadius:12,borderWidth:1,borderColor:selected?colors.primary:colors.line,backgroundColor:selected?colors.primaryLight:colors.surface,opacity:pressed?.65:1},style]}>{Icon&&<Icon size={15} color={colors.primary}/>}<Text variant="small" style={{color:selected?colors.primary:colors.muted,fontFamily:fonts.medium}}>{label}</Text></Pressable>}
export function SectionTitle({title,subtitle,action,onAction}:{title:string;subtitle?:string;action?:string;onAction?:()=>void}) {const{colors}=useTheme();return <View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:18}}><View style={{flex:1}}><Text variant="title">{title}</Text>{subtitle&&<Text variant="small" muted style={{marginTop:5}}>{subtitle}</Text>}</View>{action&&<Pressable accessibilityRole="button" onPress={onAction} style={{minHeight:44,flexDirection:'row',alignItems:'center',gap:8}}><Text variant="small" style={{color:colors.primary,fontFamily:fonts.medium}}>{action}</Text><ArrowRight size={15} color={colors.primary}/></Pressable>}</View>}
export function EmptyState({title,description,action,onAction,icon:Icon}:{title:string;description:string;action?:string;onAction?:()=>void;icon?:LucideIcon}) {const{colors}=useTheme();return <View style={{padding:36,alignItems:'center',gap:12}}>{Icon&&<View style={{width:60,height:60,alignItems:'center',justifyContent:'center',backgroundColor:colors.primaryLight,borderRadius:30,marginBottom:6}}><Icon size={25} color={colors.primary}/></View>}<Text variant="title" style={{textAlign:'center'}}>{title}</Text><Text muted style={{textAlign:'center',maxWidth:320}}>{description}</Text>{action&&onAction&&<Button label={action} onPress={onAction} style={{marginTop:8}}/>}</View>}
export function Modal({visible,onClose,title,subtitle,children,wide=false}:{visible:boolean;onClose:()=>void;title?:string;subtitle?:string;children:React.ReactNode;wide?:boolean}) {const{colors}=useTheme();return <RNModal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={{flex:1,backgroundColor:'rgba(20,36,27,0.42)',justifyContent:'center',alignItems:'center',padding:20}}><Pressable onPress={onClose} accessibilityLabel="Close dialog" style={StyleSheet.absoluteFill}/><View accessibilityViewIsModal style={{width:'100%',maxWidth:wide?680:510,maxHeight:'92%',borderRadius:28,backgroundColor:colors.background,overflow:'hidden',borderWidth:1,borderColor:colors.line}}><View style={{flexDirection:'row',paddingHorizontal:28,paddingTop:22,paddingBottom:16,alignItems:'flex-start',gap:12}}><View style={{flex:1}}>{title&&<Text variant="heading">{title}</Text>}{subtitle&&<Text muted variant="small" style={{marginTop:5}}>{subtitle}</Text>}</View><IconButton icon={X} label="Close dialog" onPress={onClose}/></View><ScrollView contentContainerStyle={{paddingHorizontal:28,paddingBottom:28}} keyboardShouldPersistTaps="handled">{children}</ScrollView></View></View></RNModal>}
export function Stepper({label,value,onChange,min=0,max=60,suffix=''}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number;suffix?:string}) {const{colors}=useTheme();return <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12}}><Text variant="label" style={{flex:1,flexShrink:1}}>{label}</Text><View style={{flexShrink:0,flexDirection:'row',alignItems:'center',gap:8,borderWidth:1,borderColor:colors.line,borderRadius:13,backgroundColor:colors.surface}}><IconButton icon={Minus} label={`Decrease ${label}`} onPress={()=>onChange(Math.max(min,value-1))}/><TextInput accessibilityLabel={label} keyboardType="number-pad" selectTextOnFocus value={String(value)} onChangeText={s=>{if(/^\d*$/.test(s))onChange(Math.min(max,Math.max(min,Number(s))))}} style={{width:34,textAlign:'center',fontFamily:fonts.medium,fontSize:15,color:colors.ink,padding:0}}/>{!!suffix&&<Text variant="small" muted>{suffix}</Text>}<IconButton icon={Plus} label={`Increase ${label}`} onPress={()=>onChange(Math.min(max,value+1))}/></View></View>}
export function Toggle({label,description,value,onChange}:{label:string;description?:string;value:boolean;onChange:(v:boolean)=>void}) {const{colors}=useTheme();return <View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:20,paddingVertical:13}}><View style={{flex:1}}><Text variant="label">{label}</Text>{description&&<Text variant="small" muted style={{marginTop:3}}>{description}</Text>}</View><Switch accessibilityLabel={label} value={value} onValueChange={onChange} trackColor={{false:colors.line,true:colors.primary}} thumbColor="#fff"/></View>}
export function Input({label,...props}:React.ComponentProps<typeof TextInput>&{label?:string}) {const{colors}=useTheme();return <View style={{gap:7}}>{label&&<Text variant="label">{label}</Text>}<TextInput accessibilityLabel={label} placeholderTextColor={colors.muted} {...props} style={[{minHeight:48,borderWidth:1,borderColor:colors.line,borderRadius:13,backgroundColor:colors.surface,paddingHorizontal:15,fontFamily:fonts.regular,fontSize:14,color:colors.ink},props.style]}/></View>}
export const Divider=()=>{const{colors}=useTheme();return <View style={{height:1,backgroundColor:colors.line,marginVertical:10}}/>};
